// rst_src.v

// Generated using ACDS version 26.1 110

`timescale 1 ps / 1 ps
module rst_src #(
		parameter ASSERT_HIGH_RESET    = 1,
		parameter INITIAL_RESET_CYCLES = 10
	) (
		output wire  reset, // reset.reset
		input  wire  clk    //   clk.clk
	);

	altera_avalon_reset_source #(
		.ASSERT_HIGH_RESET    (ASSERT_HIGH_RESET),
		.INITIAL_RESET_CYCLES (INITIAL_RESET_CYCLES)
	) rst_src (
		.reset (reset), //  output,  width = 1, reset.reset
		.clk   (clk)    //   input,  width = 1,   clk.clk
	);

endmodule
