// pd_test.v

// Generated using ACDS version 26.1 110

`timescale 1 ps / 1 ps
module pd_test (
	);

	wire          clk_src1_clk_clk;                                                 // clk_src1:clk -> [axi4_mgr_wide:clk, axi4_sub_wide:clk, mm_interconnect_0:clk_src1_clk_clk, rst_controller_002:clk, rst_src:clk]
	wire          clk_src2_clk_clk;                                                 // clk_src2:clk -> [axi4_mgr_narrow:clk, mm_interconnect_0:clk_src2_clk_clk, rst_controller:clk, rst_controller_001:clk]
	wire          rst_src_reset_reset;                                              // rst_src:reset -> [axi4_mgr_wide:rstn, axi4_sub_wide:rstn, rst_controller:reset_in0, rst_controller_001:reset_in0, rst_controller_002:reset_in0]
	wire   [31:0] axi4_mgr_narrow_altera_axi4_manager_ruser;                        // mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_ruser -> axi4_mgr_narrow:ruser
	wire   [31:0] axi4_mgr_narrow_altera_axi4_manager_wuser;                        // axi4_mgr_narrow:wuser -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_wuser
	wire    [1:0] axi4_mgr_narrow_altera_axi4_manager_awburst;                      // axi4_mgr_narrow:awburst -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_awburst
	wire    [3:0] axi4_mgr_narrow_altera_axi4_manager_arregion;                     // axi4_mgr_narrow:arregion -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_arregion
	wire    [7:0] axi4_mgr_narrow_altera_axi4_manager_arlen;                        // axi4_mgr_narrow:arlen -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_arlen
	wire    [3:0] axi4_mgr_narrow_altera_axi4_manager_arqos;                        // axi4_mgr_narrow:arqos -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_arqos
	wire   [31:0] axi4_mgr_narrow_altera_axi4_manager_awuser;                       // axi4_mgr_narrow:awuser -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_awuser
	wire          axi4_mgr_narrow_altera_axi4_manager_wready;                       // mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_wready -> axi4_mgr_narrow:wready
	wire    [3:0] axi4_mgr_narrow_altera_axi4_manager_wstrb;                        // axi4_mgr_narrow:wstrb -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_wstrb
	wire    [3:0] axi4_mgr_narrow_altera_axi4_manager_rid;                          // mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_rid -> axi4_mgr_narrow:rid
	wire          axi4_mgr_narrow_altera_axi4_manager_rready;                       // axi4_mgr_narrow:rready -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_rready
	wire    [7:0] axi4_mgr_narrow_altera_axi4_manager_awlen;                        // axi4_mgr_narrow:awlen -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_awlen
	wire    [3:0] axi4_mgr_narrow_altera_axi4_manager_awqos;                        // axi4_mgr_narrow:awqos -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_awqos
	wire    [3:0] axi4_mgr_narrow_altera_axi4_manager_arcache;                      // axi4_mgr_narrow:arcache -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_arcache
	wire          axi4_mgr_narrow_altera_axi4_manager_wvalid;                       // axi4_mgr_narrow:wvalid -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_wvalid
	wire   [22:0] axi4_mgr_narrow_altera_axi4_manager_araddr;                       // axi4_mgr_narrow:araddr -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_araddr
	wire    [2:0] axi4_mgr_narrow_altera_axi4_manager_arprot;                       // axi4_mgr_narrow:arprot -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_arprot
	wire    [2:0] axi4_mgr_narrow_altera_axi4_manager_awprot;                       // axi4_mgr_narrow:awprot -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_awprot
	wire          axi4_mgr_narrow_altera_axi4_manager_arvalid;                      // axi4_mgr_narrow:arvalid -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_arvalid
	wire   [31:0] axi4_mgr_narrow_altera_axi4_manager_wdata;                        // axi4_mgr_narrow:wdata -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_wdata
	wire    [3:0] axi4_mgr_narrow_altera_axi4_manager_awcache;                      // axi4_mgr_narrow:awcache -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_awcache
	wire    [3:0] axi4_mgr_narrow_altera_axi4_manager_arid;                         // axi4_mgr_narrow:arid -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_arid
	wire          axi4_mgr_narrow_altera_axi4_manager_arlock;                       // axi4_mgr_narrow:arlock -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_arlock
	wire          axi4_mgr_narrow_altera_axi4_manager_awlock;                       // axi4_mgr_narrow:awlock -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_awlock
	wire   [22:0] axi4_mgr_narrow_altera_axi4_manager_awaddr;                       // axi4_mgr_narrow:awaddr -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_awaddr
	wire          axi4_mgr_narrow_altera_axi4_manager_arready;                      // mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_arready -> axi4_mgr_narrow:arready
	wire    [1:0] axi4_mgr_narrow_altera_axi4_manager_bresp;                        // mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_bresp -> axi4_mgr_narrow:bresp
	wire   [31:0] axi4_mgr_narrow_altera_axi4_manager_rdata;                        // mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_rdata -> axi4_mgr_narrow:rdata
	wire          axi4_mgr_narrow_altera_axi4_manager_awready;                      // mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_awready -> axi4_mgr_narrow:awready
	wire    [1:0] axi4_mgr_narrow_altera_axi4_manager_arburst;                      // axi4_mgr_narrow:arburst -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_arburst
	wire    [2:0] axi4_mgr_narrow_altera_axi4_manager_arsize;                       // axi4_mgr_narrow:arsize -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_arsize
	wire          axi4_mgr_narrow_altera_axi4_manager_rlast;                        // mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_rlast -> axi4_mgr_narrow:rlast
	wire          axi4_mgr_narrow_altera_axi4_manager_bready;                       // axi4_mgr_narrow:bready -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_bready
	wire          axi4_mgr_narrow_altera_axi4_manager_wlast;                        // axi4_mgr_narrow:wlast -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_wlast
	wire    [3:0] axi4_mgr_narrow_altera_axi4_manager_awregion;                     // axi4_mgr_narrow:awregion -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_awregion
	wire   [31:0] axi4_mgr_narrow_altera_axi4_manager_buser;                        // mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_buser -> axi4_mgr_narrow:buser
	wire    [1:0] axi4_mgr_narrow_altera_axi4_manager_rresp;                        // mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_rresp -> axi4_mgr_narrow:rresp
	wire    [3:0] axi4_mgr_narrow_altera_axi4_manager_awid;                         // axi4_mgr_narrow:awid -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_awid
	wire    [3:0] axi4_mgr_narrow_altera_axi4_manager_bid;                          // mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_bid -> axi4_mgr_narrow:bid
	wire          axi4_mgr_narrow_altera_axi4_manager_bvalid;                       // mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_bvalid -> axi4_mgr_narrow:bvalid
	wire    [2:0] axi4_mgr_narrow_altera_axi4_manager_awsize;                       // axi4_mgr_narrow:awsize -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_awsize
	wire          axi4_mgr_narrow_altera_axi4_manager_awvalid;                      // axi4_mgr_narrow:awvalid -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_awvalid
	wire          axi4_mgr_narrow_altera_axi4_manager_rvalid;                       // mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_rvalid -> axi4_mgr_narrow:rvalid
	wire   [31:0] axi4_mgr_narrow_altera_axi4_manager_aruser;                       // axi4_mgr_narrow:aruser -> mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_aruser
	wire   [31:0] axi4_mgr_wide_altera_axi4_manager_ruser;                          // mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_ruser -> axi4_mgr_wide:ruser
	wire   [31:0] axi4_mgr_wide_altera_axi4_manager_wuser;                          // axi4_mgr_wide:wuser -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_wuser
	wire    [1:0] axi4_mgr_wide_altera_axi4_manager_awburst;                        // axi4_mgr_wide:awburst -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_awburst
	wire    [3:0] axi4_mgr_wide_altera_axi4_manager_arregion;                       // axi4_mgr_wide:arregion -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_arregion
	wire    [7:0] axi4_mgr_wide_altera_axi4_manager_arlen;                          // axi4_mgr_wide:arlen -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_arlen
	wire    [3:0] axi4_mgr_wide_altera_axi4_manager_arqos;                          // axi4_mgr_wide:arqos -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_arqos
	wire   [31:0] axi4_mgr_wide_altera_axi4_manager_awuser;                         // axi4_mgr_wide:awuser -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_awuser
	wire          axi4_mgr_wide_altera_axi4_manager_wready;                         // mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_wready -> axi4_mgr_wide:wready
	wire   [31:0] axi4_mgr_wide_altera_axi4_manager_wstrb;                          // axi4_mgr_wide:wstrb -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_wstrb
	wire    [3:0] axi4_mgr_wide_altera_axi4_manager_rid;                            // mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_rid -> axi4_mgr_wide:rid
	wire          axi4_mgr_wide_altera_axi4_manager_rready;                         // axi4_mgr_wide:rready -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_rready
	wire    [7:0] axi4_mgr_wide_altera_axi4_manager_awlen;                          // axi4_mgr_wide:awlen -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_awlen
	wire    [3:0] axi4_mgr_wide_altera_axi4_manager_awqos;                          // axi4_mgr_wide:awqos -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_awqos
	wire    [3:0] axi4_mgr_wide_altera_axi4_manager_arcache;                        // axi4_mgr_wide:arcache -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_arcache
	wire          axi4_mgr_wide_altera_axi4_manager_wvalid;                         // axi4_mgr_wide:wvalid -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_wvalid
	wire   [19:0] axi4_mgr_wide_altera_axi4_manager_araddr;                         // axi4_mgr_wide:araddr -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_araddr
	wire    [2:0] axi4_mgr_wide_altera_axi4_manager_arprot;                         // axi4_mgr_wide:arprot -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_arprot
	wire    [2:0] axi4_mgr_wide_altera_axi4_manager_awprot;                         // axi4_mgr_wide:awprot -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_awprot
	wire          axi4_mgr_wide_altera_axi4_manager_arvalid;                        // axi4_mgr_wide:arvalid -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_arvalid
	wire  [255:0] axi4_mgr_wide_altera_axi4_manager_wdata;                          // axi4_mgr_wide:wdata -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_wdata
	wire    [3:0] axi4_mgr_wide_altera_axi4_manager_awcache;                        // axi4_mgr_wide:awcache -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_awcache
	wire    [3:0] axi4_mgr_wide_altera_axi4_manager_arid;                           // axi4_mgr_wide:arid -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_arid
	wire          axi4_mgr_wide_altera_axi4_manager_arlock;                         // axi4_mgr_wide:arlock -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_arlock
	wire          axi4_mgr_wide_altera_axi4_manager_awlock;                         // axi4_mgr_wide:awlock -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_awlock
	wire   [19:0] axi4_mgr_wide_altera_axi4_manager_awaddr;                         // axi4_mgr_wide:awaddr -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_awaddr
	wire          axi4_mgr_wide_altera_axi4_manager_arready;                        // mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_arready -> axi4_mgr_wide:arready
	wire    [1:0] axi4_mgr_wide_altera_axi4_manager_bresp;                          // mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_bresp -> axi4_mgr_wide:bresp
	wire  [255:0] axi4_mgr_wide_altera_axi4_manager_rdata;                          // mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_rdata -> axi4_mgr_wide:rdata
	wire          axi4_mgr_wide_altera_axi4_manager_awready;                        // mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_awready -> axi4_mgr_wide:awready
	wire    [1:0] axi4_mgr_wide_altera_axi4_manager_arburst;                        // axi4_mgr_wide:arburst -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_arburst
	wire    [2:0] axi4_mgr_wide_altera_axi4_manager_arsize;                         // axi4_mgr_wide:arsize -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_arsize
	wire          axi4_mgr_wide_altera_axi4_manager_rlast;                          // mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_rlast -> axi4_mgr_wide:rlast
	wire          axi4_mgr_wide_altera_axi4_manager_bready;                         // axi4_mgr_wide:bready -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_bready
	wire          axi4_mgr_wide_altera_axi4_manager_wlast;                          // axi4_mgr_wide:wlast -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_wlast
	wire    [3:0] axi4_mgr_wide_altera_axi4_manager_awregion;                       // axi4_mgr_wide:awregion -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_awregion
	wire   [31:0] axi4_mgr_wide_altera_axi4_manager_buser;                          // mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_buser -> axi4_mgr_wide:buser
	wire    [1:0] axi4_mgr_wide_altera_axi4_manager_rresp;                          // mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_rresp -> axi4_mgr_wide:rresp
	wire    [3:0] axi4_mgr_wide_altera_axi4_manager_awid;                           // axi4_mgr_wide:awid -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_awid
	wire    [3:0] axi4_mgr_wide_altera_axi4_manager_bid;                            // mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_bid -> axi4_mgr_wide:bid
	wire          axi4_mgr_wide_altera_axi4_manager_bvalid;                         // mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_bvalid -> axi4_mgr_wide:bvalid
	wire    [2:0] axi4_mgr_wide_altera_axi4_manager_awsize;                         // axi4_mgr_wide:awsize -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_awsize
	wire          axi4_mgr_wide_altera_axi4_manager_awvalid;                        // axi4_mgr_wide:awvalid -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_awvalid
	wire          axi4_mgr_wide_altera_axi4_manager_rvalid;                         // mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_rvalid -> axi4_mgr_wide:rvalid
	wire   [31:0] axi4_mgr_wide_altera_axi4_manager_aruser;                         // axi4_mgr_wide:aruser -> mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_aruser
	wire   [31:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_ruser;    // axi4_sub_wide:ruser -> mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_ruser
	wire   [31:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wuser;    // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_wuser -> axi4_sub_wide:wuser
	wire    [1:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awburst;  // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_awburst -> axi4_sub_wide:awburst
	wire    [3:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arregion; // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_arregion -> axi4_sub_wide:arregion
	wire   [31:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awuser;   // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_awuser -> axi4_sub_wide:awuser
	wire    [7:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arlen;    // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_arlen -> axi4_sub_wide:arlen
	wire    [3:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arqos;    // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_arqos -> axi4_sub_wide:arqos
	wire   [31:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wstrb;    // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_wstrb -> axi4_sub_wide:wstrb
	wire          mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wready;   // axi4_sub_wide:wready -> mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_wready
	wire    [4:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rid;      // axi4_sub_wide:rid -> mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_rid
	wire          mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rready;   // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_rready -> axi4_sub_wide:rready
	wire    [7:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awlen;    // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_awlen -> axi4_sub_wide:awlen
	wire    [3:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awqos;    // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_awqos -> axi4_sub_wide:awqos
	wire    [3:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arcache;  // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_arcache -> axi4_sub_wide:arcache
	wire          mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wvalid;   // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_wvalid -> axi4_sub_wide:wvalid
	wire   [19:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_araddr;   // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_araddr -> axi4_sub_wide:araddr
	wire    [2:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arprot;   // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_arprot -> axi4_sub_wide:arprot
	wire    [2:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awprot;   // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_awprot -> axi4_sub_wide:awprot
	wire  [255:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wdata;    // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_wdata -> axi4_sub_wide:wdata
	wire          mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arvalid;  // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_arvalid -> axi4_sub_wide:arvalid
	wire    [3:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awcache;  // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_awcache -> axi4_sub_wide:awcache
	wire    [4:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arid;     // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_arid -> axi4_sub_wide:arid
	wire    [0:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arlock;   // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_arlock -> axi4_sub_wide:arlock
	wire    [0:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awlock;   // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_awlock -> axi4_sub_wide:awlock
	wire   [19:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awaddr;   // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_awaddr -> axi4_sub_wide:awaddr
	wire    [1:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_bresp;    // axi4_sub_wide:bresp -> mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_bresp
	wire          mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arready;  // axi4_sub_wide:arready -> mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_arready
	wire  [255:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rdata;    // axi4_sub_wide:rdata -> mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_rdata
	wire          mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awready;  // axi4_sub_wide:awready -> mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_awready
	wire    [1:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arburst;  // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_arburst -> axi4_sub_wide:arburst
	wire    [2:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arsize;   // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_arsize -> axi4_sub_wide:arsize
	wire          mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_bready;   // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_bready -> axi4_sub_wide:bready
	wire          mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rlast;    // axi4_sub_wide:rlast -> mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_rlast
	wire          mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wlast;    // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_wlast -> axi4_sub_wide:wlast
	wire    [3:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awregion; // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_awregion -> axi4_sub_wide:awregion
	wire   [31:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_buser;    // axi4_sub_wide:buser -> mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_buser
	wire    [1:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rresp;    // axi4_sub_wide:rresp -> mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_rresp
	wire    [4:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awid;     // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_awid -> axi4_sub_wide:awid
	wire    [4:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_bid;      // axi4_sub_wide:bid -> mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_bid
	wire          mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_bvalid;   // axi4_sub_wide:bvalid -> mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_bvalid
	wire    [2:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awsize;   // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_awsize -> axi4_sub_wide:awsize
	wire          mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awvalid;  // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_awvalid -> axi4_sub_wide:awvalid
	wire   [31:0] mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_aruser;   // mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_aruser -> axi4_sub_wide:aruser
	wire          mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rvalid;   // axi4_sub_wide:rvalid -> mm_interconnect_0:axi4_sub_wide_altera_axi4_subordinate_rvalid
	wire          rst_controller_reset_out_reset;                                   // rst_controller:reset_out -> axi4_mgr_narrow:rstn
	wire          rst_controller_001_reset_out_reset;                               // rst_controller_001:reset_out -> [mm_interconnect_0:axi4_mgr_narrow_altera_axi4_manager_translator_clk_reset_reset_bridge_in_reset_reset, mm_interconnect_0:axi4_mgr_narrow_reset_sink_reset_bridge_in_reset_reset]
	wire          rst_controller_002_reset_out_reset;                               // rst_controller_002:reset_out -> [mm_interconnect_0:axi4_mgr_wide_altera_axi4_manager_translator_clk_reset_reset_bridge_in_reset_reset, mm_interconnect_0:axi4_mgr_wide_reset_sink_reset_bridge_in_reset_reset]

	axi4_mgr_narrow axi4_mgr_narrow (
		.awlen    (axi4_mgr_narrow_altera_axi4_manager_awlen),    //  output,   width = 8, altera_axi4_manager.awlen
		.awsize   (axi4_mgr_narrow_altera_axi4_manager_awsize),   //  output,   width = 3,                    .awsize
		.awburst  (axi4_mgr_narrow_altera_axi4_manager_awburst),  //  output,   width = 2,                    .awburst
		.awvalid  (axi4_mgr_narrow_altera_axi4_manager_awvalid),  //  output,   width = 1,                    .awvalid
		.awlock   (axi4_mgr_narrow_altera_axi4_manager_awlock),   //  output,   width = 1,                    .awlock
		.awregion (axi4_mgr_narrow_altera_axi4_manager_awregion), //  output,   width = 4,                    .awregion
		.awprot   (axi4_mgr_narrow_altera_axi4_manager_awprot),   //  output,   width = 3,                    .awprot
		.awready  (axi4_mgr_narrow_altera_axi4_manager_awready),  //   input,   width = 1,                    .awready
		.arlen    (axi4_mgr_narrow_altera_axi4_manager_arlen),    //  output,   width = 8,                    .arlen
		.arsize   (axi4_mgr_narrow_altera_axi4_manager_arsize),   //  output,   width = 3,                    .arsize
		.arburst  (axi4_mgr_narrow_altera_axi4_manager_arburst),  //  output,   width = 2,                    .arburst
		.arvalid  (axi4_mgr_narrow_altera_axi4_manager_arvalid),  //  output,   width = 1,                    .arvalid
		.arlock   (axi4_mgr_narrow_altera_axi4_manager_arlock),   //  output,   width = 1,                    .arlock
		.awcache  (axi4_mgr_narrow_altera_axi4_manager_awcache),  //  output,   width = 4,                    .awcache
		.awqos    (axi4_mgr_narrow_altera_axi4_manager_awqos),    //  output,   width = 4,                    .awqos
		.arregion (axi4_mgr_narrow_altera_axi4_manager_arregion), //  output,   width = 4,                    .arregion
		.arprot   (axi4_mgr_narrow_altera_axi4_manager_arprot),   //  output,   width = 3,                    .arprot
		.arready  (axi4_mgr_narrow_altera_axi4_manager_arready),  //   input,   width = 1,                    .arready
		.rresp    (axi4_mgr_narrow_altera_axi4_manager_rresp),    //   input,   width = 2,                    .rresp
		.rvalid   (axi4_mgr_narrow_altera_axi4_manager_rvalid),   //   input,   width = 1,                    .rvalid
		.rlast    (axi4_mgr_narrow_altera_axi4_manager_rlast),    //   input,   width = 1,                    .rlast
		.rready   (axi4_mgr_narrow_altera_axi4_manager_rready),   //  output,   width = 1,                    .rready
		.wvalid   (axi4_mgr_narrow_altera_axi4_manager_wvalid),   //  output,   width = 1,                    .wvalid
		.wlast    (axi4_mgr_narrow_altera_axi4_manager_wlast),    //  output,   width = 1,                    .wlast
		.wready   (axi4_mgr_narrow_altera_axi4_manager_wready),   //   input,   width = 1,                    .wready
		.bresp    (axi4_mgr_narrow_altera_axi4_manager_bresp),    //   input,   width = 2,                    .bresp
		.bvalid   (axi4_mgr_narrow_altera_axi4_manager_bvalid),   //   input,   width = 1,                    .bvalid
		.bready   (axi4_mgr_narrow_altera_axi4_manager_bready),   //  output,   width = 1,                    .bready
		.arcache  (axi4_mgr_narrow_altera_axi4_manager_arcache),  //  output,   width = 4,                    .arcache
		.arqos    (axi4_mgr_narrow_altera_axi4_manager_arqos),    //  output,   width = 4,                    .arqos
		.awaddr   (axi4_mgr_narrow_altera_axi4_manager_awaddr),   //  output,  width = 23,                    .awaddr
		.awid     (axi4_mgr_narrow_altera_axi4_manager_awid),     //  output,   width = 4,                    .awid
		.awuser   (axi4_mgr_narrow_altera_axi4_manager_awuser),   //  output,  width = 32,                    .awuser
		.araddr   (axi4_mgr_narrow_altera_axi4_manager_araddr),   //  output,  width = 23,                    .araddr
		.arid     (axi4_mgr_narrow_altera_axi4_manager_arid),     //  output,   width = 4,                    .arid
		.aruser   (axi4_mgr_narrow_altera_axi4_manager_aruser),   //  output,  width = 32,                    .aruser
		.ruser    (axi4_mgr_narrow_altera_axi4_manager_ruser),    //   input,  width = 32,                    .ruser
		.wuser    (axi4_mgr_narrow_altera_axi4_manager_wuser),    //  output,  width = 32,                    .wuser
		.buser    (axi4_mgr_narrow_altera_axi4_manager_buser),    //   input,  width = 32,                    .buser
		.rdata    (axi4_mgr_narrow_altera_axi4_manager_rdata),    //   input,  width = 32,                    .rdata
		.rid      (axi4_mgr_narrow_altera_axi4_manager_rid),      //   input,   width = 4,                    .rid
		.wdata    (axi4_mgr_narrow_altera_axi4_manager_wdata),    //  output,  width = 32,                    .wdata
		.wstrb    (axi4_mgr_narrow_altera_axi4_manager_wstrb),    //  output,   width = 4,                    .wstrb
		.bid      (axi4_mgr_narrow_altera_axi4_manager_bid),      //   input,   width = 4,                    .bid
		.clk      (clk_src2_clk_clk),                             //   input,   width = 1,          clock_sink.clk
		.rstn     (~rst_controller_reset_out_reset)               //   input,   width = 1,          reset_sink.reset_n
	);

	axi4_mgr axi4_mgr_wide (
		.awlen    (axi4_mgr_wide_altera_axi4_manager_awlen),    //  output,    width = 8, altera_axi4_manager.awlen
		.awsize   (axi4_mgr_wide_altera_axi4_manager_awsize),   //  output,    width = 3,                    .awsize
		.awburst  (axi4_mgr_wide_altera_axi4_manager_awburst),  //  output,    width = 2,                    .awburst
		.awvalid  (axi4_mgr_wide_altera_axi4_manager_awvalid),  //  output,    width = 1,                    .awvalid
		.awlock   (axi4_mgr_wide_altera_axi4_manager_awlock),   //  output,    width = 1,                    .awlock
		.awregion (axi4_mgr_wide_altera_axi4_manager_awregion), //  output,    width = 4,                    .awregion
		.awprot   (axi4_mgr_wide_altera_axi4_manager_awprot),   //  output,    width = 3,                    .awprot
		.awready  (axi4_mgr_wide_altera_axi4_manager_awready),  //   input,    width = 1,                    .awready
		.arlen    (axi4_mgr_wide_altera_axi4_manager_arlen),    //  output,    width = 8,                    .arlen
		.arsize   (axi4_mgr_wide_altera_axi4_manager_arsize),   //  output,    width = 3,                    .arsize
		.arburst  (axi4_mgr_wide_altera_axi4_manager_arburst),  //  output,    width = 2,                    .arburst
		.arvalid  (axi4_mgr_wide_altera_axi4_manager_arvalid),  //  output,    width = 1,                    .arvalid
		.arlock   (axi4_mgr_wide_altera_axi4_manager_arlock),   //  output,    width = 1,                    .arlock
		.awcache  (axi4_mgr_wide_altera_axi4_manager_awcache),  //  output,    width = 4,                    .awcache
		.awqos    (axi4_mgr_wide_altera_axi4_manager_awqos),    //  output,    width = 4,                    .awqos
		.arregion (axi4_mgr_wide_altera_axi4_manager_arregion), //  output,    width = 4,                    .arregion
		.arprot   (axi4_mgr_wide_altera_axi4_manager_arprot),   //  output,    width = 3,                    .arprot
		.arready  (axi4_mgr_wide_altera_axi4_manager_arready),  //   input,    width = 1,                    .arready
		.rresp    (axi4_mgr_wide_altera_axi4_manager_rresp),    //   input,    width = 2,                    .rresp
		.rvalid   (axi4_mgr_wide_altera_axi4_manager_rvalid),   //   input,    width = 1,                    .rvalid
		.rlast    (axi4_mgr_wide_altera_axi4_manager_rlast),    //   input,    width = 1,                    .rlast
		.rready   (axi4_mgr_wide_altera_axi4_manager_rready),   //  output,    width = 1,                    .rready
		.wvalid   (axi4_mgr_wide_altera_axi4_manager_wvalid),   //  output,    width = 1,                    .wvalid
		.wlast    (axi4_mgr_wide_altera_axi4_manager_wlast),    //  output,    width = 1,                    .wlast
		.wready   (axi4_mgr_wide_altera_axi4_manager_wready),   //   input,    width = 1,                    .wready
		.bresp    (axi4_mgr_wide_altera_axi4_manager_bresp),    //   input,    width = 2,                    .bresp
		.bvalid   (axi4_mgr_wide_altera_axi4_manager_bvalid),   //   input,    width = 1,                    .bvalid
		.bready   (axi4_mgr_wide_altera_axi4_manager_bready),   //  output,    width = 1,                    .bready
		.arcache  (axi4_mgr_wide_altera_axi4_manager_arcache),  //  output,    width = 4,                    .arcache
		.arqos    (axi4_mgr_wide_altera_axi4_manager_arqos),    //  output,    width = 4,                    .arqos
		.awaddr   (axi4_mgr_wide_altera_axi4_manager_awaddr),   //  output,   width = 20,                    .awaddr
		.awid     (axi4_mgr_wide_altera_axi4_manager_awid),     //  output,    width = 4,                    .awid
		.awuser   (axi4_mgr_wide_altera_axi4_manager_awuser),   //  output,   width = 32,                    .awuser
		.araddr   (axi4_mgr_wide_altera_axi4_manager_araddr),   //  output,   width = 20,                    .araddr
		.arid     (axi4_mgr_wide_altera_axi4_manager_arid),     //  output,    width = 4,                    .arid
		.aruser   (axi4_mgr_wide_altera_axi4_manager_aruser),   //  output,   width = 32,                    .aruser
		.ruser    (axi4_mgr_wide_altera_axi4_manager_ruser),    //   input,   width = 32,                    .ruser
		.wuser    (axi4_mgr_wide_altera_axi4_manager_wuser),    //  output,   width = 32,                    .wuser
		.buser    (axi4_mgr_wide_altera_axi4_manager_buser),    //   input,   width = 32,                    .buser
		.rdata    (axi4_mgr_wide_altera_axi4_manager_rdata),    //   input,  width = 256,                    .rdata
		.rid      (axi4_mgr_wide_altera_axi4_manager_rid),      //   input,    width = 4,                    .rid
		.wdata    (axi4_mgr_wide_altera_axi4_manager_wdata),    //  output,  width = 256,                    .wdata
		.wstrb    (axi4_mgr_wide_altera_axi4_manager_wstrb),    //  output,   width = 32,                    .wstrb
		.bid      (axi4_mgr_wide_altera_axi4_manager_bid),      //   input,    width = 4,                    .bid
		.clk      (clk_src1_clk_clk),                           //   input,    width = 1,          clock_sink.clk
		.rstn     (~rst_src_reset_reset)                        //   input,    width = 1,          reset_sink.reset_n
	);

	axi4_sub_wide axi4_sub_wide (
		.awlen    (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awlen),    //   input,    width = 8, altera_axi4_subordinate.awlen
		.awsize   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awsize),   //   input,    width = 3,                        .awsize
		.awburst  (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awburst),  //   input,    width = 2,                        .awburst
		.awvalid  (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awvalid),  //   input,    width = 1,                        .awvalid
		.awlock   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awlock),   //   input,    width = 1,                        .awlock
		.awregion (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awregion), //   input,    width = 4,                        .awregion
		.awprot   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awprot),   //   input,    width = 3,                        .awprot
		.awready  (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awready),  //  output,    width = 1,                        .awready
		.arlen    (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arlen),    //   input,    width = 8,                        .arlen
		.arsize   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arsize),   //   input,    width = 3,                        .arsize
		.arburst  (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arburst),  //   input,    width = 2,                        .arburst
		.arvalid  (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arvalid),  //   input,    width = 1,                        .arvalid
		.arlock   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arlock),   //   input,    width = 1,                        .arlock
		.arregion (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arregion), //   input,    width = 4,                        .arregion
		.awcache  (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awcache),  //   input,    width = 4,                        .awcache
		.awqos    (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awqos),    //   input,    width = 4,                        .awqos
		.arprot   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arprot),   //   input,    width = 3,                        .arprot
		.arready  (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arready),  //  output,    width = 1,                        .arready
		.rvalid   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rvalid),   //  output,    width = 1,                        .rvalid
		.rlast    (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rlast),    //  output,    width = 1,                        .rlast
		.rresp    (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rresp),    //  output,    width = 2,                        .rresp
		.rready   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rready),   //   input,    width = 1,                        .rready
		.wvalid   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wvalid),   //   input,    width = 1,                        .wvalid
		.wlast    (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wlast),    //   input,    width = 1,                        .wlast
		.wready   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wready),   //  output,    width = 1,                        .wready
		.bresp    (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_bresp),    //  output,    width = 2,                        .bresp
		.bvalid   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_bvalid),   //  output,    width = 1,                        .bvalid
		.bready   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_bready),   //   input,    width = 1,                        .bready
		.arcache  (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arcache),  //   input,    width = 4,                        .arcache
		.arqos    (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arqos),    //   input,    width = 4,                        .arqos
		.awaddr   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awaddr),   //   input,   width = 20,                        .awaddr
		.awid     (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awid),     //   input,    width = 5,                        .awid
		.awuser   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awuser),   //   input,   width = 32,                        .awuser
		.araddr   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_araddr),   //   input,   width = 20,                        .araddr
		.arid     (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arid),     //   input,    width = 5,                        .arid
		.aruser   (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_aruser),   //   input,   width = 32,                        .aruser
		.ruser    (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_ruser),    //  output,   width = 32,                        .ruser
		.wuser    (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wuser),    //   input,   width = 32,                        .wuser
		.buser    (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_buser),    //  output,   width = 32,                        .buser
		.rdata    (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rdata),    //  output,  width = 256,                        .rdata
		.rid      (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rid),      //  output,    width = 5,                        .rid
		.wdata    (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wdata),    //   input,  width = 256,                        .wdata
		.wstrb    (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wstrb),    //   input,   width = 32,                        .wstrb
		.bid      (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_bid),      //  output,    width = 5,                        .bid
		.clk      (clk_src1_clk_clk),                                                 //   input,    width = 1,              clock_sink.clk
		.rstn     (~rst_src_reset_reset)                                              //   input,    width = 1,              reset_sink.reset_n
	);

	clk_src1 clk_src1 (
		.clk (clk_src1_clk_clk)  //  output,  width = 1, clk.clk
	);

	clk_src2 clk_src2 (
		.clk (clk_src2_clk_clk)  //  output,  width = 1, clk.clk
	);

	rst_src rst_src (
		.reset (rst_src_reset_reset), //  output,  width = 1, reset.reset
		.clk   (clk_src1_clk_clk)     //   input,  width = 1,   clk.clk
	);

	pd_test_stim stim();

	pd_test_altera_mm_interconnect_1920_6srq35i mm_interconnect_0 (
		.axi4_mgr_narrow_altera_axi4_manager_awid                                             (axi4_mgr_narrow_altera_axi4_manager_awid),                         //   input,    width = 4,                                            axi4_mgr_narrow_altera_axi4_manager.awid
		.axi4_mgr_narrow_altera_axi4_manager_awaddr                                           (axi4_mgr_narrow_altera_axi4_manager_awaddr),                       //   input,   width = 23,                                                                               .awaddr
		.axi4_mgr_narrow_altera_axi4_manager_awlen                                            (axi4_mgr_narrow_altera_axi4_manager_awlen),                        //   input,    width = 8,                                                                               .awlen
		.axi4_mgr_narrow_altera_axi4_manager_awsize                                           (axi4_mgr_narrow_altera_axi4_manager_awsize),                       //   input,    width = 3,                                                                               .awsize
		.axi4_mgr_narrow_altera_axi4_manager_awburst                                          (axi4_mgr_narrow_altera_axi4_manager_awburst),                      //   input,    width = 2,                                                                               .awburst
		.axi4_mgr_narrow_altera_axi4_manager_awlock                                           (axi4_mgr_narrow_altera_axi4_manager_awlock),                       //   input,    width = 1,                                                                               .awlock
		.axi4_mgr_narrow_altera_axi4_manager_awcache                                          (axi4_mgr_narrow_altera_axi4_manager_awcache),                      //   input,    width = 4,                                                                               .awcache
		.axi4_mgr_narrow_altera_axi4_manager_awprot                                           (axi4_mgr_narrow_altera_axi4_manager_awprot),                       //   input,    width = 3,                                                                               .awprot
		.axi4_mgr_narrow_altera_axi4_manager_awuser                                           (axi4_mgr_narrow_altera_axi4_manager_awuser),                       //   input,   width = 32,                                                                               .awuser
		.axi4_mgr_narrow_altera_axi4_manager_awqos                                            (axi4_mgr_narrow_altera_axi4_manager_awqos),                        //   input,    width = 4,                                                                               .awqos
		.axi4_mgr_narrow_altera_axi4_manager_awregion                                         (axi4_mgr_narrow_altera_axi4_manager_awregion),                     //   input,    width = 4,                                                                               .awregion
		.axi4_mgr_narrow_altera_axi4_manager_awvalid                                          (axi4_mgr_narrow_altera_axi4_manager_awvalid),                      //   input,    width = 1,                                                                               .awvalid
		.axi4_mgr_narrow_altera_axi4_manager_awready                                          (axi4_mgr_narrow_altera_axi4_manager_awready),                      //  output,    width = 1,                                                                               .awready
		.axi4_mgr_narrow_altera_axi4_manager_wdata                                            (axi4_mgr_narrow_altera_axi4_manager_wdata),                        //   input,   width = 32,                                                                               .wdata
		.axi4_mgr_narrow_altera_axi4_manager_wstrb                                            (axi4_mgr_narrow_altera_axi4_manager_wstrb),                        //   input,    width = 4,                                                                               .wstrb
		.axi4_mgr_narrow_altera_axi4_manager_wlast                                            (axi4_mgr_narrow_altera_axi4_manager_wlast),                        //   input,    width = 1,                                                                               .wlast
		.axi4_mgr_narrow_altera_axi4_manager_wvalid                                           (axi4_mgr_narrow_altera_axi4_manager_wvalid),                       //   input,    width = 1,                                                                               .wvalid
		.axi4_mgr_narrow_altera_axi4_manager_wuser                                            (axi4_mgr_narrow_altera_axi4_manager_wuser),                        //   input,   width = 32,                                                                               .wuser
		.axi4_mgr_narrow_altera_axi4_manager_wready                                           (axi4_mgr_narrow_altera_axi4_manager_wready),                       //  output,    width = 1,                                                                               .wready
		.axi4_mgr_narrow_altera_axi4_manager_bid                                              (axi4_mgr_narrow_altera_axi4_manager_bid),                          //  output,    width = 4,                                                                               .bid
		.axi4_mgr_narrow_altera_axi4_manager_bresp                                            (axi4_mgr_narrow_altera_axi4_manager_bresp),                        //  output,    width = 2,                                                                               .bresp
		.axi4_mgr_narrow_altera_axi4_manager_buser                                            (axi4_mgr_narrow_altera_axi4_manager_buser),                        //  output,   width = 32,                                                                               .buser
		.axi4_mgr_narrow_altera_axi4_manager_bvalid                                           (axi4_mgr_narrow_altera_axi4_manager_bvalid),                       //  output,    width = 1,                                                                               .bvalid
		.axi4_mgr_narrow_altera_axi4_manager_bready                                           (axi4_mgr_narrow_altera_axi4_manager_bready),                       //   input,    width = 1,                                                                               .bready
		.axi4_mgr_narrow_altera_axi4_manager_arid                                             (axi4_mgr_narrow_altera_axi4_manager_arid),                         //   input,    width = 4,                                                                               .arid
		.axi4_mgr_narrow_altera_axi4_manager_araddr                                           (axi4_mgr_narrow_altera_axi4_manager_araddr),                       //   input,   width = 23,                                                                               .araddr
		.axi4_mgr_narrow_altera_axi4_manager_arlen                                            (axi4_mgr_narrow_altera_axi4_manager_arlen),                        //   input,    width = 8,                                                                               .arlen
		.axi4_mgr_narrow_altera_axi4_manager_arsize                                           (axi4_mgr_narrow_altera_axi4_manager_arsize),                       //   input,    width = 3,                                                                               .arsize
		.axi4_mgr_narrow_altera_axi4_manager_arburst                                          (axi4_mgr_narrow_altera_axi4_manager_arburst),                      //   input,    width = 2,                                                                               .arburst
		.axi4_mgr_narrow_altera_axi4_manager_arlock                                           (axi4_mgr_narrow_altera_axi4_manager_arlock),                       //   input,    width = 1,                                                                               .arlock
		.axi4_mgr_narrow_altera_axi4_manager_arcache                                          (axi4_mgr_narrow_altera_axi4_manager_arcache),                      //   input,    width = 4,                                                                               .arcache
		.axi4_mgr_narrow_altera_axi4_manager_arprot                                           (axi4_mgr_narrow_altera_axi4_manager_arprot),                       //   input,    width = 3,                                                                               .arprot
		.axi4_mgr_narrow_altera_axi4_manager_aruser                                           (axi4_mgr_narrow_altera_axi4_manager_aruser),                       //   input,   width = 32,                                                                               .aruser
		.axi4_mgr_narrow_altera_axi4_manager_arqos                                            (axi4_mgr_narrow_altera_axi4_manager_arqos),                        //   input,    width = 4,                                                                               .arqos
		.axi4_mgr_narrow_altera_axi4_manager_arregion                                         (axi4_mgr_narrow_altera_axi4_manager_arregion),                     //   input,    width = 4,                                                                               .arregion
		.axi4_mgr_narrow_altera_axi4_manager_arvalid                                          (axi4_mgr_narrow_altera_axi4_manager_arvalid),                      //   input,    width = 1,                                                                               .arvalid
		.axi4_mgr_narrow_altera_axi4_manager_arready                                          (axi4_mgr_narrow_altera_axi4_manager_arready),                      //  output,    width = 1,                                                                               .arready
		.axi4_mgr_narrow_altera_axi4_manager_rid                                              (axi4_mgr_narrow_altera_axi4_manager_rid),                          //  output,    width = 4,                                                                               .rid
		.axi4_mgr_narrow_altera_axi4_manager_rdata                                            (axi4_mgr_narrow_altera_axi4_manager_rdata),                        //  output,   width = 32,                                                                               .rdata
		.axi4_mgr_narrow_altera_axi4_manager_rresp                                            (axi4_mgr_narrow_altera_axi4_manager_rresp),                        //  output,    width = 2,                                                                               .rresp
		.axi4_mgr_narrow_altera_axi4_manager_rlast                                            (axi4_mgr_narrow_altera_axi4_manager_rlast),                        //  output,    width = 1,                                                                               .rlast
		.axi4_mgr_narrow_altera_axi4_manager_rvalid                                           (axi4_mgr_narrow_altera_axi4_manager_rvalid),                       //  output,    width = 1,                                                                               .rvalid
		.axi4_mgr_narrow_altera_axi4_manager_rready                                           (axi4_mgr_narrow_altera_axi4_manager_rready),                       //   input,    width = 1,                                                                               .rready
		.axi4_mgr_narrow_altera_axi4_manager_ruser                                            (axi4_mgr_narrow_altera_axi4_manager_ruser),                        //  output,   width = 32,                                                                               .ruser
		.axi4_mgr_wide_altera_axi4_manager_awid                                               (axi4_mgr_wide_altera_axi4_manager_awid),                           //   input,    width = 4,                                              axi4_mgr_wide_altera_axi4_manager.awid
		.axi4_mgr_wide_altera_axi4_manager_awaddr                                             (axi4_mgr_wide_altera_axi4_manager_awaddr),                         //   input,   width = 20,                                                                               .awaddr
		.axi4_mgr_wide_altera_axi4_manager_awlen                                              (axi4_mgr_wide_altera_axi4_manager_awlen),                          //   input,    width = 8,                                                                               .awlen
		.axi4_mgr_wide_altera_axi4_manager_awsize                                             (axi4_mgr_wide_altera_axi4_manager_awsize),                         //   input,    width = 3,                                                                               .awsize
		.axi4_mgr_wide_altera_axi4_manager_awburst                                            (axi4_mgr_wide_altera_axi4_manager_awburst),                        //   input,    width = 2,                                                                               .awburst
		.axi4_mgr_wide_altera_axi4_manager_awlock                                             (axi4_mgr_wide_altera_axi4_manager_awlock),                         //   input,    width = 1,                                                                               .awlock
		.axi4_mgr_wide_altera_axi4_manager_awcache                                            (axi4_mgr_wide_altera_axi4_manager_awcache),                        //   input,    width = 4,                                                                               .awcache
		.axi4_mgr_wide_altera_axi4_manager_awprot                                             (axi4_mgr_wide_altera_axi4_manager_awprot),                         //   input,    width = 3,                                                                               .awprot
		.axi4_mgr_wide_altera_axi4_manager_awuser                                             (axi4_mgr_wide_altera_axi4_manager_awuser),                         //   input,   width = 32,                                                                               .awuser
		.axi4_mgr_wide_altera_axi4_manager_awqos                                              (axi4_mgr_wide_altera_axi4_manager_awqos),                          //   input,    width = 4,                                                                               .awqos
		.axi4_mgr_wide_altera_axi4_manager_awregion                                           (axi4_mgr_wide_altera_axi4_manager_awregion),                       //   input,    width = 4,                                                                               .awregion
		.axi4_mgr_wide_altera_axi4_manager_awvalid                                            (axi4_mgr_wide_altera_axi4_manager_awvalid),                        //   input,    width = 1,                                                                               .awvalid
		.axi4_mgr_wide_altera_axi4_manager_awready                                            (axi4_mgr_wide_altera_axi4_manager_awready),                        //  output,    width = 1,                                                                               .awready
		.axi4_mgr_wide_altera_axi4_manager_wdata                                              (axi4_mgr_wide_altera_axi4_manager_wdata),                          //   input,  width = 256,                                                                               .wdata
		.axi4_mgr_wide_altera_axi4_manager_wstrb                                              (axi4_mgr_wide_altera_axi4_manager_wstrb),                          //   input,   width = 32,                                                                               .wstrb
		.axi4_mgr_wide_altera_axi4_manager_wlast                                              (axi4_mgr_wide_altera_axi4_manager_wlast),                          //   input,    width = 1,                                                                               .wlast
		.axi4_mgr_wide_altera_axi4_manager_wvalid                                             (axi4_mgr_wide_altera_axi4_manager_wvalid),                         //   input,    width = 1,                                                                               .wvalid
		.axi4_mgr_wide_altera_axi4_manager_wuser                                              (axi4_mgr_wide_altera_axi4_manager_wuser),                          //   input,   width = 32,                                                                               .wuser
		.axi4_mgr_wide_altera_axi4_manager_wready                                             (axi4_mgr_wide_altera_axi4_manager_wready),                         //  output,    width = 1,                                                                               .wready
		.axi4_mgr_wide_altera_axi4_manager_bid                                                (axi4_mgr_wide_altera_axi4_manager_bid),                            //  output,    width = 4,                                                                               .bid
		.axi4_mgr_wide_altera_axi4_manager_bresp                                              (axi4_mgr_wide_altera_axi4_manager_bresp),                          //  output,    width = 2,                                                                               .bresp
		.axi4_mgr_wide_altera_axi4_manager_buser                                              (axi4_mgr_wide_altera_axi4_manager_buser),                          //  output,   width = 32,                                                                               .buser
		.axi4_mgr_wide_altera_axi4_manager_bvalid                                             (axi4_mgr_wide_altera_axi4_manager_bvalid),                         //  output,    width = 1,                                                                               .bvalid
		.axi4_mgr_wide_altera_axi4_manager_bready                                             (axi4_mgr_wide_altera_axi4_manager_bready),                         //   input,    width = 1,                                                                               .bready
		.axi4_mgr_wide_altera_axi4_manager_arid                                               (axi4_mgr_wide_altera_axi4_manager_arid),                           //   input,    width = 4,                                                                               .arid
		.axi4_mgr_wide_altera_axi4_manager_araddr                                             (axi4_mgr_wide_altera_axi4_manager_araddr),                         //   input,   width = 20,                                                                               .araddr
		.axi4_mgr_wide_altera_axi4_manager_arlen                                              (axi4_mgr_wide_altera_axi4_manager_arlen),                          //   input,    width = 8,                                                                               .arlen
		.axi4_mgr_wide_altera_axi4_manager_arsize                                             (axi4_mgr_wide_altera_axi4_manager_arsize),                         //   input,    width = 3,                                                                               .arsize
		.axi4_mgr_wide_altera_axi4_manager_arburst                                            (axi4_mgr_wide_altera_axi4_manager_arburst),                        //   input,    width = 2,                                                                               .arburst
		.axi4_mgr_wide_altera_axi4_manager_arlock                                             (axi4_mgr_wide_altera_axi4_manager_arlock),                         //   input,    width = 1,                                                                               .arlock
		.axi4_mgr_wide_altera_axi4_manager_arcache                                            (axi4_mgr_wide_altera_axi4_manager_arcache),                        //   input,    width = 4,                                                                               .arcache
		.axi4_mgr_wide_altera_axi4_manager_arprot                                             (axi4_mgr_wide_altera_axi4_manager_arprot),                         //   input,    width = 3,                                                                               .arprot
		.axi4_mgr_wide_altera_axi4_manager_aruser                                             (axi4_mgr_wide_altera_axi4_manager_aruser),                         //   input,   width = 32,                                                                               .aruser
		.axi4_mgr_wide_altera_axi4_manager_arqos                                              (axi4_mgr_wide_altera_axi4_manager_arqos),                          //   input,    width = 4,                                                                               .arqos
		.axi4_mgr_wide_altera_axi4_manager_arregion                                           (axi4_mgr_wide_altera_axi4_manager_arregion),                       //   input,    width = 4,                                                                               .arregion
		.axi4_mgr_wide_altera_axi4_manager_arvalid                                            (axi4_mgr_wide_altera_axi4_manager_arvalid),                        //   input,    width = 1,                                                                               .arvalid
		.axi4_mgr_wide_altera_axi4_manager_arready                                            (axi4_mgr_wide_altera_axi4_manager_arready),                        //  output,    width = 1,                                                                               .arready
		.axi4_mgr_wide_altera_axi4_manager_rid                                                (axi4_mgr_wide_altera_axi4_manager_rid),                            //  output,    width = 4,                                                                               .rid
		.axi4_mgr_wide_altera_axi4_manager_rdata                                              (axi4_mgr_wide_altera_axi4_manager_rdata),                          //  output,  width = 256,                                                                               .rdata
		.axi4_mgr_wide_altera_axi4_manager_rresp                                              (axi4_mgr_wide_altera_axi4_manager_rresp),                          //  output,    width = 2,                                                                               .rresp
		.axi4_mgr_wide_altera_axi4_manager_rlast                                              (axi4_mgr_wide_altera_axi4_manager_rlast),                          //  output,    width = 1,                                                                               .rlast
		.axi4_mgr_wide_altera_axi4_manager_rvalid                                             (axi4_mgr_wide_altera_axi4_manager_rvalid),                         //  output,    width = 1,                                                                               .rvalid
		.axi4_mgr_wide_altera_axi4_manager_rready                                             (axi4_mgr_wide_altera_axi4_manager_rready),                         //   input,    width = 1,                                                                               .rready
		.axi4_mgr_wide_altera_axi4_manager_ruser                                              (axi4_mgr_wide_altera_axi4_manager_ruser),                          //  output,   width = 32,                                                                               .ruser
		.axi4_sub_wide_altera_axi4_subordinate_awid                                           (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awid),     //  output,    width = 5,                                          axi4_sub_wide_altera_axi4_subordinate.awid
		.axi4_sub_wide_altera_axi4_subordinate_awaddr                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awaddr),   //  output,   width = 20,                                                                               .awaddr
		.axi4_sub_wide_altera_axi4_subordinate_awlen                                          (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awlen),    //  output,    width = 8,                                                                               .awlen
		.axi4_sub_wide_altera_axi4_subordinate_awsize                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awsize),   //  output,    width = 3,                                                                               .awsize
		.axi4_sub_wide_altera_axi4_subordinate_awburst                                        (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awburst),  //  output,    width = 2,                                                                               .awburst
		.axi4_sub_wide_altera_axi4_subordinate_awlock                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awlock),   //  output,    width = 1,                                                                               .awlock
		.axi4_sub_wide_altera_axi4_subordinate_awcache                                        (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awcache),  //  output,    width = 4,                                                                               .awcache
		.axi4_sub_wide_altera_axi4_subordinate_awprot                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awprot),   //  output,    width = 3,                                                                               .awprot
		.axi4_sub_wide_altera_axi4_subordinate_awuser                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awuser),   //  output,   width = 32,                                                                               .awuser
		.axi4_sub_wide_altera_axi4_subordinate_awqos                                          (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awqos),    //  output,    width = 4,                                                                               .awqos
		.axi4_sub_wide_altera_axi4_subordinate_awregion                                       (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awregion), //  output,    width = 4,                                                                               .awregion
		.axi4_sub_wide_altera_axi4_subordinate_awvalid                                        (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awvalid),  //  output,    width = 1,                                                                               .awvalid
		.axi4_sub_wide_altera_axi4_subordinate_awready                                        (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_awready),  //   input,    width = 1,                                                                               .awready
		.axi4_sub_wide_altera_axi4_subordinate_wdata                                          (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wdata),    //  output,  width = 256,                                                                               .wdata
		.axi4_sub_wide_altera_axi4_subordinate_wstrb                                          (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wstrb),    //  output,   width = 32,                                                                               .wstrb
		.axi4_sub_wide_altera_axi4_subordinate_wlast                                          (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wlast),    //  output,    width = 1,                                                                               .wlast
		.axi4_sub_wide_altera_axi4_subordinate_wvalid                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wvalid),   //  output,    width = 1,                                                                               .wvalid
		.axi4_sub_wide_altera_axi4_subordinate_wuser                                          (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wuser),    //  output,   width = 32,                                                                               .wuser
		.axi4_sub_wide_altera_axi4_subordinate_wready                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_wready),   //   input,    width = 1,                                                                               .wready
		.axi4_sub_wide_altera_axi4_subordinate_bid                                            (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_bid),      //   input,    width = 5,                                                                               .bid
		.axi4_sub_wide_altera_axi4_subordinate_bresp                                          (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_bresp),    //   input,    width = 2,                                                                               .bresp
		.axi4_sub_wide_altera_axi4_subordinate_buser                                          (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_buser),    //   input,   width = 32,                                                                               .buser
		.axi4_sub_wide_altera_axi4_subordinate_bvalid                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_bvalid),   //   input,    width = 1,                                                                               .bvalid
		.axi4_sub_wide_altera_axi4_subordinate_bready                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_bready),   //  output,    width = 1,                                                                               .bready
		.axi4_sub_wide_altera_axi4_subordinate_arid                                           (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arid),     //  output,    width = 5,                                                                               .arid
		.axi4_sub_wide_altera_axi4_subordinate_araddr                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_araddr),   //  output,   width = 20,                                                                               .araddr
		.axi4_sub_wide_altera_axi4_subordinate_arlen                                          (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arlen),    //  output,    width = 8,                                                                               .arlen
		.axi4_sub_wide_altera_axi4_subordinate_arsize                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arsize),   //  output,    width = 3,                                                                               .arsize
		.axi4_sub_wide_altera_axi4_subordinate_arburst                                        (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arburst),  //  output,    width = 2,                                                                               .arburst
		.axi4_sub_wide_altera_axi4_subordinate_arlock                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arlock),   //  output,    width = 1,                                                                               .arlock
		.axi4_sub_wide_altera_axi4_subordinate_arcache                                        (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arcache),  //  output,    width = 4,                                                                               .arcache
		.axi4_sub_wide_altera_axi4_subordinate_arprot                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arprot),   //  output,    width = 3,                                                                               .arprot
		.axi4_sub_wide_altera_axi4_subordinate_aruser                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_aruser),   //  output,   width = 32,                                                                               .aruser
		.axi4_sub_wide_altera_axi4_subordinate_arqos                                          (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arqos),    //  output,    width = 4,                                                                               .arqos
		.axi4_sub_wide_altera_axi4_subordinate_arregion                                       (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arregion), //  output,    width = 4,                                                                               .arregion
		.axi4_sub_wide_altera_axi4_subordinate_arvalid                                        (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arvalid),  //  output,    width = 1,                                                                               .arvalid
		.axi4_sub_wide_altera_axi4_subordinate_arready                                        (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_arready),  //   input,    width = 1,                                                                               .arready
		.axi4_sub_wide_altera_axi4_subordinate_rid                                            (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rid),      //   input,    width = 5,                                                                               .rid
		.axi4_sub_wide_altera_axi4_subordinate_rdata                                          (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rdata),    //   input,  width = 256,                                                                               .rdata
		.axi4_sub_wide_altera_axi4_subordinate_rresp                                          (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rresp),    //   input,    width = 2,                                                                               .rresp
		.axi4_sub_wide_altera_axi4_subordinate_rlast                                          (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rlast),    //   input,    width = 1,                                                                               .rlast
		.axi4_sub_wide_altera_axi4_subordinate_rvalid                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rvalid),   //   input,    width = 1,                                                                               .rvalid
		.axi4_sub_wide_altera_axi4_subordinate_rready                                         (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_rready),   //  output,    width = 1,                                                                               .rready
		.axi4_sub_wide_altera_axi4_subordinate_ruser                                          (mm_interconnect_0_axi4_sub_wide_altera_axi4_subordinate_ruser),    //   input,   width = 32,                                                                               .ruser
		.axi4_mgr_narrow_reset_sink_reset_bridge_in_reset_reset                               (rst_controller_001_reset_out_reset),                               //   input,    width = 1,                               axi4_mgr_narrow_reset_sink_reset_bridge_in_reset.reset
		.axi4_mgr_wide_reset_sink_reset_bridge_in_reset_reset                                 (rst_controller_002_reset_out_reset),                               //   input,    width = 1,                                 axi4_mgr_wide_reset_sink_reset_bridge_in_reset.reset
		.axi4_mgr_narrow_altera_axi4_manager_translator_clk_reset_reset_bridge_in_reset_reset (rst_controller_001_reset_out_reset),                               //   input,    width = 1, axi4_mgr_narrow_altera_axi4_manager_translator_clk_reset_reset_bridge_in_reset.reset
		.axi4_mgr_wide_altera_axi4_manager_translator_clk_reset_reset_bridge_in_reset_reset   (rst_controller_002_reset_out_reset),                               //   input,    width = 1,   axi4_mgr_wide_altera_axi4_manager_translator_clk_reset_reset_bridge_in_reset.reset
		.clk_src2_clk_clk                                                                     (clk_src2_clk_clk),                                                 //   input,    width = 1,                                                                   clk_src2_clk.clk
		.clk_src1_clk_clk                                                                     (clk_src1_clk_clk)                                                  //   input,    width = 1,                                                                   clk_src1_clk.clk
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (rst_src_reset_reset),            //   input,  width = 1, reset_in0.reset
		.clk            (clk_src2_clk_clk),               //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                               // (terminated),                       
		.reset_req_in0  (1'b0),                           // (terminated),                       
		.reset_in1      (1'b0),                           // (terminated),                       
		.reset_req_in1  (1'b0),                           // (terminated),                       
		.reset_in2      (1'b0),                           // (terminated),                       
		.reset_req_in2  (1'b0),                           // (terminated),                       
		.reset_in3      (1'b0),                           // (terminated),                       
		.reset_req_in3  (1'b0),                           // (terminated),                       
		.reset_in4      (1'b0),                           // (terminated),                       
		.reset_req_in4  (1'b0),                           // (terminated),                       
		.reset_in5      (1'b0),                           // (terminated),                       
		.reset_req_in5  (1'b0),                           // (terminated),                       
		.reset_in6      (1'b0),                           // (terminated),                       
		.reset_req_in6  (1'b0),                           // (terminated),                       
		.reset_in7      (1'b0),                           // (terminated),                       
		.reset_req_in7  (1'b0),                           // (terminated),                       
		.reset_in8      (1'b0),                           // (terminated),                       
		.reset_req_in8  (1'b0),                           // (terminated),                       
		.reset_in9      (1'b0),                           // (terminated),                       
		.reset_req_in9  (1'b0),                           // (terminated),                       
		.reset_in10     (1'b0),                           // (terminated),                       
		.reset_req_in10 (1'b0),                           // (terminated),                       
		.reset_in11     (1'b0),                           // (terminated),                       
		.reset_req_in11 (1'b0),                           // (terminated),                       
		.reset_in12     (1'b0),                           // (terminated),                       
		.reset_req_in12 (1'b0),                           // (terminated),                       
		.reset_in13     (1'b0),                           // (terminated),                       
		.reset_req_in13 (1'b0),                           // (terminated),                       
		.reset_in14     (1'b0),                           // (terminated),                       
		.reset_req_in14 (1'b0),                           // (terminated),                       
		.reset_in15     (1'b0),                           // (terminated),                       
		.reset_req_in15 (1'b0)                            // (terminated),                       
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("both"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (rst_src_reset_reset),                //   input,  width = 1, reset_in0.reset
		.clk            (clk_src2_clk_clk),                   //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                                   // (terminated),                       
		.reset_req_in0  (1'b0),                               // (terminated),                       
		.reset_in1      (1'b0),                               // (terminated),                       
		.reset_req_in1  (1'b0),                               // (terminated),                       
		.reset_in2      (1'b0),                               // (terminated),                       
		.reset_req_in2  (1'b0),                               // (terminated),                       
		.reset_in3      (1'b0),                               // (terminated),                       
		.reset_req_in3  (1'b0),                               // (terminated),                       
		.reset_in4      (1'b0),                               // (terminated),                       
		.reset_req_in4  (1'b0),                               // (terminated),                       
		.reset_in5      (1'b0),                               // (terminated),                       
		.reset_req_in5  (1'b0),                               // (terminated),                       
		.reset_in6      (1'b0),                               // (terminated),                       
		.reset_req_in6  (1'b0),                               // (terminated),                       
		.reset_in7      (1'b0),                               // (terminated),                       
		.reset_req_in7  (1'b0),                               // (terminated),                       
		.reset_in8      (1'b0),                               // (terminated),                       
		.reset_req_in8  (1'b0),                               // (terminated),                       
		.reset_in9      (1'b0),                               // (terminated),                       
		.reset_req_in9  (1'b0),                               // (terminated),                       
		.reset_in10     (1'b0),                               // (terminated),                       
		.reset_req_in10 (1'b0),                               // (terminated),                       
		.reset_in11     (1'b0),                               // (terminated),                       
		.reset_req_in11 (1'b0),                               // (terminated),                       
		.reset_in12     (1'b0),                               // (terminated),                       
		.reset_req_in12 (1'b0),                               // (terminated),                       
		.reset_in13     (1'b0),                               // (terminated),                       
		.reset_req_in13 (1'b0),                               // (terminated),                       
		.reset_in14     (1'b0),                               // (terminated),                       
		.reset_req_in14 (1'b0),                               // (terminated),                       
		.reset_in15     (1'b0),                               // (terminated),                       
		.reset_req_in15 (1'b0)                                // (terminated),                       
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("both"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_002 (
		.reset_in0      (rst_src_reset_reset),                //   input,  width = 1, reset_in0.reset
		.clk            (clk_src1_clk_clk),                   //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_002_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                                   // (terminated),                       
		.reset_req_in0  (1'b0),                               // (terminated),                       
		.reset_in1      (1'b0),                               // (terminated),                       
		.reset_req_in1  (1'b0),                               // (terminated),                       
		.reset_in2      (1'b0),                               // (terminated),                       
		.reset_req_in2  (1'b0),                               // (terminated),                       
		.reset_in3      (1'b0),                               // (terminated),                       
		.reset_req_in3  (1'b0),                               // (terminated),                       
		.reset_in4      (1'b0),                               // (terminated),                       
		.reset_req_in4  (1'b0),                               // (terminated),                       
		.reset_in5      (1'b0),                               // (terminated),                       
		.reset_req_in5  (1'b0),                               // (terminated),                       
		.reset_in6      (1'b0),                               // (terminated),                       
		.reset_req_in6  (1'b0),                               // (terminated),                       
		.reset_in7      (1'b0),                               // (terminated),                       
		.reset_req_in7  (1'b0),                               // (terminated),                       
		.reset_in8      (1'b0),                               // (terminated),                       
		.reset_req_in8  (1'b0),                               // (terminated),                       
		.reset_in9      (1'b0),                               // (terminated),                       
		.reset_req_in9  (1'b0),                               // (terminated),                       
		.reset_in10     (1'b0),                               // (terminated),                       
		.reset_req_in10 (1'b0),                               // (terminated),                       
		.reset_in11     (1'b0),                               // (terminated),                       
		.reset_req_in11 (1'b0),                               // (terminated),                       
		.reset_in12     (1'b0),                               // (terminated),                       
		.reset_req_in12 (1'b0),                               // (terminated),                       
		.reset_in13     (1'b0),                               // (terminated),                       
		.reset_req_in13 (1'b0),                               // (terminated),                       
		.reset_in14     (1'b0),                               // (terminated),                       
		.reset_req_in14 (1'b0),                               // (terminated),                       
		.reset_in15     (1'b0),                               // (terminated),                       
		.reset_req_in15 (1'b0)                                // (terminated),                       
	);

endmodule
