// axi4_mgr.v

// Generated using ACDS version 26.1 110

`timescale 1 ps / 1 ps
module axi4_mgr #(
		parameter ADDR_WIDTH                  = 20,
		parameter DATA_WIDTH                  = 256,
		parameter ID_WIDTH                    = 4,
		parameter USER_WIDTH                  = 32,
		parameter RD_ISSUING_CAPABILITY       = 16,
		parameter WR_ISSUING_CAPABILITY       = 16,
		parameter COMBINED_ISSUING_CAPABILITY = 16,
		parameter USE_AWID                    = 1,
		parameter USE_AWREGION                = 1,
		parameter USE_AWLEN                   = 1,
		parameter USE_AWSIZE                  = 1,
		parameter USE_AWBURST                 = 1,
		parameter USE_AWLOCK                  = 1,
		parameter USE_AWCACHE                 = 1,
		parameter USE_AWQOS                   = 1,
		parameter USE_WSTRB                   = 1,
		parameter USE_BID                     = 1,
		parameter USE_BRESP                   = 1,
		parameter USE_ARID                    = 1,
		parameter USE_ARREGION                = 1,
		parameter USE_ARLEN                   = 1,
		parameter USE_ARSIZE                  = 1,
		parameter USE_ARBURST                 = 1,
		parameter USE_ARLOCK                  = 1,
		parameter USE_ARCACHE                 = 1,
		parameter USE_ARQOS                   = 1,
		parameter USE_RID                     = 1,
		parameter USE_RRESP                   = 1,
		parameter USE_RLAST                   = 1,
		parameter USE_AWUSER                  = 1,
		parameter USE_ARUSER                  = 1,
		parameter USE_WUSER                   = 1,
		parameter USE_RUSER                   = 1,
		parameter USE_BUSER                   = 1
	) (
		output wire [7:0]   awlen,    // altera_axi4_manager.awlen
		output wire [2:0]   awsize,   //                    .awsize
		output wire [1:0]   awburst,  //                    .awburst
		output wire         awvalid,  //                    .awvalid
		output wire         awlock,   //                    .awlock
		output wire [3:0]   awregion, //                    .awregion
		output wire [2:0]   awprot,   //                    .awprot
		input  wire         awready,  //                    .awready
		output wire [7:0]   arlen,    //                    .arlen
		output wire [2:0]   arsize,   //                    .arsize
		output wire [1:0]   arburst,  //                    .arburst
		output wire         arvalid,  //                    .arvalid
		output wire         arlock,   //                    .arlock
		output wire [3:0]   awcache,  //                    .awcache
		output wire [3:0]   awqos,    //                    .awqos
		output wire [3:0]   arregion, //                    .arregion
		output wire [2:0]   arprot,   //                    .arprot
		input  wire         arready,  //                    .arready
		input  wire [1:0]   rresp,    //                    .rresp
		input  wire         rvalid,   //                    .rvalid
		input  wire         rlast,    //                    .rlast
		output wire         rready,   //                    .rready
		output wire         wvalid,   //                    .wvalid
		output wire         wlast,    //                    .wlast
		input  wire         wready,   //                    .wready
		input  wire [1:0]   bresp,    //                    .bresp
		input  wire         bvalid,   //                    .bvalid
		output wire         bready,   //                    .bready
		output wire [3:0]   arcache,  //                    .arcache
		output wire [3:0]   arqos,    //                    .arqos
		output wire [19:0]  awaddr,   //                    .awaddr
		output wire [3:0]   awid,     //                    .awid
		output wire [31:0]  awuser,   //                    .awuser
		output wire [19:0]  araddr,   //                    .araddr
		output wire [3:0]   arid,     //                    .arid
		output wire [31:0]  aruser,   //                    .aruser
		input  wire [31:0]  ruser,    //                    .ruser
		output wire [31:0]  wuser,    //                    .wuser
		input  wire [31:0]  buser,    //                    .buser
		input  wire [255:0] rdata,    //                    .rdata
		input  wire [3:0]   rid,      //                    .rid
		output wire [255:0] wdata,    //                    .wdata
		output wire [31:0]  wstrb,    //                    .wstrb
		input  wire [3:0]   bid,      //                    .bid
		input  wire         clk,      //          clock_sink.clk
		input  wire         rstn      //          reset_sink.reset_n
	);

	altera_axi4_mm_manager #(
		.ADDR_WIDTH                  (ADDR_WIDTH),
		.DATA_WIDTH                  (DATA_WIDTH),
		.ID_WIDTH                    (ID_WIDTH),
		.USER_WIDTH                  (USER_WIDTH),
		.RD_ISSUING_CAPABILITY       (RD_ISSUING_CAPABILITY),
		.WR_ISSUING_CAPABILITY       (WR_ISSUING_CAPABILITY),
		.COMBINED_ISSUING_CAPABILITY (COMBINED_ISSUING_CAPABILITY),
		.USE_AWID                    (USE_AWID),
		.USE_AWREGION                (USE_AWREGION),
		.USE_AWLEN                   (USE_AWLEN),
		.USE_AWSIZE                  (USE_AWSIZE),
		.USE_AWBURST                 (USE_AWBURST),
		.USE_AWLOCK                  (USE_AWLOCK),
		.USE_AWCACHE                 (USE_AWCACHE),
		.USE_AWQOS                   (USE_AWQOS),
		.USE_WSTRB                   (USE_WSTRB),
		.USE_BID                     (USE_BID),
		.USE_BRESP                   (USE_BRESP),
		.USE_ARID                    (USE_ARID),
		.USE_ARREGION                (USE_ARREGION),
		.USE_ARLEN                   (USE_ARLEN),
		.USE_ARSIZE                  (USE_ARSIZE),
		.USE_ARBURST                 (USE_ARBURST),
		.USE_ARLOCK                  (USE_ARLOCK),
		.USE_ARCACHE                 (USE_ARCACHE),
		.USE_ARQOS                   (USE_ARQOS),
		.USE_RID                     (USE_RID),
		.USE_RRESP                   (USE_RRESP),
		.USE_RLAST                   (USE_RLAST),
		.USE_AWUSER                  (USE_AWUSER),
		.USE_ARUSER                  (USE_ARUSER),
		.USE_WUSER                   (USE_WUSER),
		.USE_RUSER                   (USE_RUSER),
		.USE_BUSER                   (USE_BUSER)
	) axi4_mgr (
		.awlen    (awlen),    //  output,    width = 8, altera_axi4_manager.awlen
		.awsize   (awsize),   //  output,    width = 3,                    .awsize
		.awburst  (awburst),  //  output,    width = 2,                    .awburst
		.awvalid  (awvalid),  //  output,    width = 1,                    .awvalid
		.awlock   (awlock),   //  output,    width = 1,                    .awlock
		.awregion (awregion), //  output,    width = 4,                    .awregion
		.awprot   (awprot),   //  output,    width = 3,                    .awprot
		.awready  (awready),  //   input,    width = 1,                    .awready
		.arlen    (arlen),    //  output,    width = 8,                    .arlen
		.arsize   (arsize),   //  output,    width = 3,                    .arsize
		.arburst  (arburst),  //  output,    width = 2,                    .arburst
		.arvalid  (arvalid),  //  output,    width = 1,                    .arvalid
		.arlock   (arlock),   //  output,    width = 1,                    .arlock
		.awcache  (awcache),  //  output,    width = 4,                    .awcache
		.awqos    (awqos),    //  output,    width = 4,                    .awqos
		.arregion (arregion), //  output,    width = 4,                    .arregion
		.arprot   (arprot),   //  output,    width = 3,                    .arprot
		.arready  (arready),  //   input,    width = 1,                    .arready
		.rresp    (rresp),    //   input,    width = 2,                    .rresp
		.rvalid   (rvalid),   //   input,    width = 1,                    .rvalid
		.rlast    (rlast),    //   input,    width = 1,                    .rlast
		.rready   (rready),   //  output,    width = 1,                    .rready
		.wvalid   (wvalid),   //  output,    width = 1,                    .wvalid
		.wlast    (wlast),    //  output,    width = 1,                    .wlast
		.wready   (wready),   //   input,    width = 1,                    .wready
		.bresp    (bresp),    //   input,    width = 2,                    .bresp
		.bvalid   (bvalid),   //   input,    width = 1,                    .bvalid
		.bready   (bready),   //  output,    width = 1,                    .bready
		.arcache  (arcache),  //  output,    width = 4,                    .arcache
		.arqos    (arqos),    //  output,    width = 4,                    .arqos
		.awaddr   (awaddr),   //  output,   width = 20,                    .awaddr
		.awid     (awid),     //  output,    width = 4,                    .awid
		.awuser   (awuser),   //  output,   width = 32,                    .awuser
		.araddr   (araddr),   //  output,   width = 20,                    .araddr
		.arid     (arid),     //  output,    width = 4,                    .arid
		.aruser   (aruser),   //  output,   width = 32,                    .aruser
		.ruser    (ruser),    //   input,   width = 32,                    .ruser
		.wuser    (wuser),    //  output,   width = 32,                    .wuser
		.buser    (buser),    //   input,   width = 32,                    .buser
		.rdata    (rdata),    //   input,  width = 256,                    .rdata
		.rid      (rid),      //   input,    width = 4,                    .rid
		.wdata    (wdata),    //  output,  width = 256,                    .wdata
		.wstrb    (wstrb),    //  output,   width = 32,                    .wstrb
		.bid      (bid),      //   input,    width = 4,                    .bid
		.clk      (clk),      //   input,    width = 1,          clock_sink.clk
		.rstn     (rstn)      //   input,    width = 1,          reset_sink.reset_n
	);

endmodule
