// axi4_sub_wide.v

// Generated using ACDS version 26.1 110

`timescale 1 ps / 1 ps
module axi4_sub_wide #(
		parameter ADDR_WIDTH                     = 20,
		parameter DATA_WIDTH                     = 256,
		parameter ID_WIDTH                       = 5,
		parameter USER_WIDTH                     = 32,
		parameter RD_ACCEPTANCE_CAPABILITY       = 16,
		parameter WR_ACCEPTANCE_CAPABILITY       = 16,
		parameter COMBINED_ACCEPTANCE_CAPABILITY = 16,
		parameter USE_AWREGION                   = 1,
		parameter USE_AWLOCK                     = 1,
		parameter USE_AWCACHE                    = 1,
		parameter USE_AWQOS                      = 1,
		parameter USE_AWPROT                     = 1,
		parameter USE_WLAST                      = 1,
		parameter USE_BRESP                      = 1,
		parameter USE_ARREGION                   = 1,
		parameter USE_ARLOCK                     = 1,
		parameter USE_ARCACHE                    = 1,
		parameter USE_ARQOS                      = 1,
		parameter USE_ARPROT                     = 1,
		parameter USE_RRESP                      = 1,
		parameter USE_AWUSER                     = 1,
		parameter USE_ARUSER                     = 1,
		parameter USE_WUSER                      = 1,
		parameter USE_RUSER                      = 1,
		parameter USE_BUSER                      = 1
	) (
		input  wire [7:0]   awlen,    // altera_axi4_subordinate.awlen
		input  wire [2:0]   awsize,   //                        .awsize
		input  wire [1:0]   awburst,  //                        .awburst
		input  wire         awvalid,  //                        .awvalid
		input  wire         awlock,   //                        .awlock
		input  wire [3:0]   awregion, //                        .awregion
		input  wire [2:0]   awprot,   //                        .awprot
		output wire         awready,  //                        .awready
		input  wire [7:0]   arlen,    //                        .arlen
		input  wire [2:0]   arsize,   //                        .arsize
		input  wire [1:0]   arburst,  //                        .arburst
		input  wire         arvalid,  //                        .arvalid
		input  wire         arlock,   //                        .arlock
		input  wire [3:0]   arregion, //                        .arregion
		input  wire [3:0]   awcache,  //                        .awcache
		input  wire [3:0]   awqos,    //                        .awqos
		input  wire [2:0]   arprot,   //                        .arprot
		output wire         arready,  //                        .arready
		output wire         rvalid,   //                        .rvalid
		output wire         rlast,    //                        .rlast
		output wire [1:0]   rresp,    //                        .rresp
		input  wire         rready,   //                        .rready
		input  wire         wvalid,   //                        .wvalid
		input  wire         wlast,    //                        .wlast
		output wire         wready,   //                        .wready
		output wire [1:0]   bresp,    //                        .bresp
		output wire         bvalid,   //                        .bvalid
		input  wire         bready,   //                        .bready
		input  wire [3:0]   arcache,  //                        .arcache
		input  wire [3:0]   arqos,    //                        .arqos
		input  wire [19:0]  awaddr,   //                        .awaddr
		input  wire [4:0]   awid,     //                        .awid
		input  wire [31:0]  awuser,   //                        .awuser
		input  wire [19:0]  araddr,   //                        .araddr
		input  wire [4:0]   arid,     //                        .arid
		input  wire [31:0]  aruser,   //                        .aruser
		output wire [31:0]  ruser,    //                        .ruser
		input  wire [31:0]  wuser,    //                        .wuser
		output wire [31:0]  buser,    //                        .buser
		output wire [255:0] rdata,    //                        .rdata
		output wire [4:0]   rid,      //                        .rid
		input  wire [255:0] wdata,    //                        .wdata
		input  wire [31:0]  wstrb,    //                        .wstrb
		output wire [4:0]   bid,      //                        .bid
		input  wire         clk,      //              clock_sink.clk
		input  wire         rstn      //              reset_sink.reset_n
	);

	altera_axi4_mm_subordinate #(
		.ADDR_WIDTH                     (ADDR_WIDTH),
		.DATA_WIDTH                     (DATA_WIDTH),
		.ID_WIDTH                       (ID_WIDTH),
		.USER_WIDTH                     (USER_WIDTH),
		.RD_ACCEPTANCE_CAPABILITY       (RD_ACCEPTANCE_CAPABILITY),
		.WR_ACCEPTANCE_CAPABILITY       (WR_ACCEPTANCE_CAPABILITY),
		.COMBINED_ACCEPTANCE_CAPABILITY (COMBINED_ACCEPTANCE_CAPABILITY),
		.USE_AWREGION                   (USE_AWREGION),
		.USE_AWLOCK                     (USE_AWLOCK),
		.USE_AWCACHE                    (USE_AWCACHE),
		.USE_AWQOS                      (USE_AWQOS),
		.USE_AWPROT                     (USE_AWPROT),
		.USE_WLAST                      (USE_WLAST),
		.USE_BRESP                      (USE_BRESP),
		.USE_ARREGION                   (USE_ARREGION),
		.USE_ARLOCK                     (USE_ARLOCK),
		.USE_ARCACHE                    (USE_ARCACHE),
		.USE_ARQOS                      (USE_ARQOS),
		.USE_ARPROT                     (USE_ARPROT),
		.USE_RRESP                      (USE_RRESP),
		.USE_AWUSER                     (USE_AWUSER),
		.USE_ARUSER                     (USE_ARUSER),
		.USE_WUSER                      (USE_WUSER),
		.USE_RUSER                      (USE_RUSER),
		.USE_BUSER                      (USE_BUSER)
	) axi4_sub_wide (
		.awlen    (awlen),    //   input,    width = 8, altera_axi4_subordinate.awlen
		.awsize   (awsize),   //   input,    width = 3,                        .awsize
		.awburst  (awburst),  //   input,    width = 2,                        .awburst
		.awvalid  (awvalid),  //   input,    width = 1,                        .awvalid
		.awlock   (awlock),   //   input,    width = 1,                        .awlock
		.awregion (awregion), //   input,    width = 4,                        .awregion
		.awprot   (awprot),   //   input,    width = 3,                        .awprot
		.awready  (awready),  //  output,    width = 1,                        .awready
		.arlen    (arlen),    //   input,    width = 8,                        .arlen
		.arsize   (arsize),   //   input,    width = 3,                        .arsize
		.arburst  (arburst),  //   input,    width = 2,                        .arburst
		.arvalid  (arvalid),  //   input,    width = 1,                        .arvalid
		.arlock   (arlock),   //   input,    width = 1,                        .arlock
		.arregion (arregion), //   input,    width = 4,                        .arregion
		.awcache  (awcache),  //   input,    width = 4,                        .awcache
		.awqos    (awqos),    //   input,    width = 4,                        .awqos
		.arprot   (arprot),   //   input,    width = 3,                        .arprot
		.arready  (arready),  //  output,    width = 1,                        .arready
		.rvalid   (rvalid),   //  output,    width = 1,                        .rvalid
		.rlast    (rlast),    //  output,    width = 1,                        .rlast
		.rresp    (rresp),    //  output,    width = 2,                        .rresp
		.rready   (rready),   //   input,    width = 1,                        .rready
		.wvalid   (wvalid),   //   input,    width = 1,                        .wvalid
		.wlast    (wlast),    //   input,    width = 1,                        .wlast
		.wready   (wready),   //  output,    width = 1,                        .wready
		.bresp    (bresp),    //  output,    width = 2,                        .bresp
		.bvalid   (bvalid),   //  output,    width = 1,                        .bvalid
		.bready   (bready),   //   input,    width = 1,                        .bready
		.arcache  (arcache),  //   input,    width = 4,                        .arcache
		.arqos    (arqos),    //   input,    width = 4,                        .arqos
		.awaddr   (awaddr),   //   input,   width = 20,                        .awaddr
		.awid     (awid),     //   input,    width = 5,                        .awid
		.awuser   (awuser),   //   input,   width = 32,                        .awuser
		.araddr   (araddr),   //   input,   width = 20,                        .araddr
		.arid     (arid),     //   input,    width = 5,                        .arid
		.aruser   (aruser),   //   input,   width = 32,                        .aruser
		.ruser    (ruser),    //  output,   width = 32,                        .ruser
		.wuser    (wuser),    //   input,   width = 32,                        .wuser
		.buser    (buser),    //  output,   width = 32,                        .buser
		.rdata    (rdata),    //  output,  width = 256,                        .rdata
		.rid      (rid),      //  output,    width = 5,                        .rid
		.wdata    (wdata),    //   input,  width = 256,                        .wdata
		.wstrb    (wstrb),    //   input,   width = 32,                        .wstrb
		.bid      (bid),      //  output,    width = 5,                        .bid
		.clk      (clk),      //   input,    width = 1,              clock_sink.clk
		.rstn     (rstn)      //   input,    width = 1,              reset_sink.reset_n
	);

endmodule
