// clk_src1.v

// Generated using ACDS version 26.1 110

`timescale 1 ps / 1 ps
module clk_src1 #(
		parameter CLOCK_RATE = 1000,
		parameter CLOCK_UNIT = 1000000
	) (
		output wire  clk  // clk.clk
	);

	altera_avalon_clock_source #(
		.CLOCK_RATE (CLOCK_RATE),
		.CLOCK_UNIT (CLOCK_UNIT)
	) clk_src1 (
		.clk (clk)  //  output,  width = 1, clk.clk
	);

endmodule
